### ISSUE TITLE
Bug: Thru Can Tp You Into Blocks.

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#115] opened 2017-07-08 03:25 UTC
Sometimes Threw Will Send You Into a 1x1x1 block i think and glitches your head in the block above.
Video: https://gyazo.com/a8919c141e48708ca8165b4e7a9ef492

**Comment by RedDiamondREC** [comment] 2017-12-16 04:43
basically make sure when you do a /threw its a 1x2x1 area not 1x1x1

**Comment by EvilPeanut** [comment] 2017-12-29 13:13
Duplicate of #71

**Closed by EvilPeanut** 2017-12-29 13:13 UTC
Labels: bug
