### ISSUE TITLE
Incorrect /thru positioning

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#71] opened 2016-08-12 12:18 UTC
I did /thru threw a 1 block wall and mutual times it has sent me threw randomly hundreds of blocks and threw the next wall the command can find instead of just one wall

**Comment by EvilPeanut** [comment] 2016-08-16 17:31
Tested and bug confirmed

**Comment by EvilPeanut** [comment] 2017-12-29 14:25
Duplicate of #106

**Closed by EvilPeanut** 2017-12-29 14:25 UTC
Labels: bug
