### ISSUE TITLE
Bug: Move Command With Data Issues.

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#119] opened 2017-07-08 03:57 UTC
Move Command Causes Data Issues and removes data items.
Video: https://gyazo.com/dba75dfc397d9716394d9c7a02b3561f

**Comment by EvilPeanut** [comment] 2017-07-10 17:09
Isn't this a minecraft command as opposed to an EvilBook command?

**Comment by RedDiamondREC** [comment] 2017-07-11 00:56
No it would be a imbue in evilbook. Possibly a issue with coping different facing of directions

**Comment by EvilPeanut** [comment] 2017-12-29 14:21
Duplicate of #131

**Closed by EvilPeanut** 2017-12-29 14:21 UTC
Labels: bug
