### ISSUE TITLE
Copy Paste Data Glitch.

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#114] opened 2017-07-08 03:21 UTC
Id's Don't Appear To Paste Right.
Video: https://gyazo.com/c599a3866fd55d5a5ab08cd4b80ebe6d

**Comment by EvilPeanut** [comment] 2017-12-29 14:21
Duplicate of #131

**Closed by EvilPeanut** 2017-12-29 14:21 UTC
Labels: bug
