### ISSUE TITLE
Bug: Flip Command Data Issue

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#117] opened 2017-07-08 03:39 UTC
Flipping Items Gives Incorrect Data And Destroys Items
Video: https://gyazo.com/9a49dd1950281a40095926900c1a3f62

**Comment by EvilPeanut** [comment] 2017-12-29 14:22
Duplicate of #131

**Closed by EvilPeanut** 2017-12-29 14:22 UTC
Labels: bug
